from typing import override
from langchain_community.utilities import (
    WikipediaAPIWrapper,
    DuckDuckGoSearchAPIWrapper,
)
from langchain_community.tools import WikipediaQueryRun, DuckDuckGoSearchRun
from openai.types.responses.response import Response
import streamlit as st
import openai, json, time

# # First, we create a EventHandler class to define
# # how we want to handle the events in the response stream.

PROMPT_NAME = "Search Prompt"


st.set_page_config(
    page_title="Prompt",
    page_icon="💬",
)


# OpenAI API key의 유효성을 검사합니다.
# 반환 값은 파일 업로더의 비활성화 여부를 결정합니다.
# disabled가 False일 때 버튼이 활성화되므로, API key가 유효하다면 False를 반환합니다.
def validate_key(api_key: str) -> bool:
    try:
        openai.OpenAI(api_key=api_key).models.list()
        return False
    except Exception as e:
        return True


with st.sidebar:
    API_KEY = st.text_input("Enter your OpenAI API key", type="password")
    is_invalid = validate_key(API_KEY)
    st.link_button(
        "Github repo",
        "https://github.com/bioroid17/nomad-gpt-challenge",
    )
    with st.expander("View source code"):
        st.markdown(
            """
```python
from typing import override
from langchain_community.utilities import (
    WikipediaAPIWrapper,
    DuckDuckGoSearchAPIWrapper,
)
from langchain_community.tools import WikipediaQueryRun, DuckDuckGoSearchRun
from openai.types.responses.response import Response
import streamlit as st
import openai, json, time

# # First, we create a EventHandler class to define
# # how we want to handle the events in the response stream.

PROMPT_NAME = "Search Prompt"


st.set_page_config(
    page_title="Prompt",
    page_icon="💬",
)


# OpenAI API key의 유효성을 검사합니다.
# 반환 값은 파일 업로더의 비활성화 여부를 결정합니다.
# disabled가 False일 때 버튼이 활성화되므로, API key가 유효하다면 False를 반환합니다.
def validate_key(api_key: str) -> bool:
    try:
        openai.OpenAI(api_key=api_key).models.list()
        return False
    except Exception as e:
        return True


with st.sidebar:
    API_KEY = st.text_input("Enter your OpenAI API key", type="password")
    is_invalid = validate_key(API_KEY)
    st.link_button(
        "Github repo",
        "https://github.com/bioroid17/nomad-gpt-challenge",
    )
    with st.expander("View source code"):
        st.markdown("Here comes the source code.")


# Tools
def wikipedia_search(inputs):
    query = inputs["query"]
    wp = WikipediaQueryRun(api_wrapper=WikipediaAPIWrapper())
    print(f"using wikipedia_search, query: {query}")
    return wp.run(query)


def duckduckgo_search(inputs):
    query = inputs["query"]
    ddg = DuckDuckGoSearchRun(api_wrapper=DuckDuckGoSearchAPIWrapper())
    urls = ddg.run(query)
    print(f"using duckduckgo_search, query: {query}")
    return urls


functions_map = {
    "wikipedia_search": wikipedia_search,
    "duckduckgo_search": duckduckgo_search,
}

functions = [
    {
        "type": "function",
        "name": "wikipedia_search",
        "description": "Given the query, return the search result from wikipedia.",
        "parameters": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "The keyword of the information you want to search.",
                }
            },
            "required": ["query"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "duckduckgo_search",
        "description": "Given the query, return the search result from duckduckgo.",
        "parameters": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "The keyword of the information you want to search.",
                }
            },
            "required": ["query"],
            "additionalProperties": False,
        },
        "strict": True,
    },
]


def get_response(input_list: list) -> Response:
    return openai.responses.create(
        model="gpt-4o-mini",
        input=input_list,
        tools=functions,
        tool_choice="required",
    )


def get_response2(input_list: list) -> Response:
    return openai.responses.create(
        model="gpt-4o-mini",
        input=input_list,
        tools=functions,
        instructions="Respond only with a result generated by a tool.",
    )


def stream_data(message: str):
    for word in message.split(" "):
        yield word + " "
        time.sleep(0.01)


def insert_message(message: str, role: str, save: bool = True) -> None:
    with st.chat_message(role):
        st.write_stream(stream_data(message))
    st.session_state["messages"].append({"message": message, "role": role})


def paint_history() -> None:
    for message in st.session_state.get("messages", []):
        with st.chat_message(message["role"]):
            st.write(message["message"])


if not is_invalid:
    openai.api_key = API_KEY

    paint_history()
    content = st.chat_input("What do you want to search?", disabled=is_invalid)
    if content:
        insert_message(content, "user")

        # Create a running input list we will add to over time
        input_list = [{"role": "user", "content": content}]
        response = get_response(input_list)

        # Save function call outputs for subsequent requests
        input_list += response.output
        for output in response.output:
            if output.type == "function_call":
                print("response type: function call")

                function_call = output
                function_name = function_call.name
                arguments = json.loads(function_call.arguments)

                # Response API의 경우 function call 처리를 위해 function call 결과를 다시 OpenAI에 넣어줘야 함
                if function_name == "wikipedia_search":
                    result = wikipedia_search(arguments)
                    input_list.append(
                        {
                            "type": "function_call_output",
                            "call_id": output.call_id,
                            "output": json.dumps({"result": result}),
                        }
                    )
                elif function_name == "duckduckgo_search":
                    result = duckduckgo_search(arguments)
                    input_list.append(
                        {
                            "type": "function_call_output",
                            "call_id": output.call_id,
                            "output": json.dumps({"result": result}),
                        }
                    )
        print(f"Final input:{input_list}")
        response2 = get_response2(input_list)
        insert_message(response2.output_text, "ai")
else:
    st.session_state["messages"] = []
    st.sidebar.warning("Input OpenAI API Key.")

```
"""
        )


# Tools
def wikipedia_search(inputs):
    query = inputs["query"]
    wp = WikipediaQueryRun(api_wrapper=WikipediaAPIWrapper())
    print(f"using wikipedia_search, query: {query}")
    return wp.run(query)


def duckduckgo_search(inputs):
    query = inputs["query"]
    ddg = DuckDuckGoSearchRun(api_wrapper=DuckDuckGoSearchAPIWrapper())
    urls = ddg.run(query)
    print(f"using duckduckgo_search, query: {query}")
    return urls


functions_map = {
    "wikipedia_search": wikipedia_search,
    "duckduckgo_search": duckduckgo_search,
}

functions = [
    {
        "type": "function",
        "name": "wikipedia_search",
        "description": "Given the query, return the search result from wikipedia.",
        "parameters": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "The keyword of the information you want to search.",
                }
            },
            "required": ["query"],
            "additionalProperties": False,
        },
        "strict": True,
    },
    {
        "type": "function",
        "name": "duckduckgo_search",
        "description": "Given the query, return the search result from duckduckgo.",
        "parameters": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "The keyword of the information you want to search.",
                }
            },
            "required": ["query"],
            "additionalProperties": False,
        },
        "strict": True,
    },
]


def get_response(input_list: list) -> Response:
    return openai.responses.create(
        model="gpt-4o-mini",
        input=input_list,
        tools=functions,
        tool_choice="required",
    )


def get_response2(input_list: list) -> Response:
    return openai.responses.create(
        model="gpt-4o-mini",
        input=input_list,
        tools=functions,
        instructions="Respond only with a result generated by a tool.",
    )


def stream_data(message: str):
    for word in message.split(" "):
        yield word + " "
        time.sleep(0.01)


def insert_message(message: str, role: str, save: bool = True) -> None:
    with st.chat_message(role):
        st.write_stream(stream_data(message))
    st.session_state["messages"].append({"message": message, "role": role})


def paint_history() -> None:
    for message in st.session_state.get("messages", []):
        with st.chat_message(message["role"]):
            st.write(message["message"])


if not is_invalid:
    openai.api_key = API_KEY

    paint_history()
    content = st.chat_input("What do you want to search?", disabled=is_invalid)
    if content:
        insert_message(content, "user")

        # Create a running input list we will add to over time
        input_list = [{"role": "user", "content": content}]
        response = get_response(input_list)

        # Save function call outputs for subsequent requests
        input_list += response.output
        for output in response.output:
            if output.type == "function_call":
                print("response type: function call")

                function_call = output
                function_name = function_call.name
                arguments = json.loads(function_call.arguments)

                # Response API의 경우 function call 처리를 위해 function call 결과를 다시 OpenAI에 넣어줘야 함
                if function_name == "wikipedia_search":
                    result = wikipedia_search(arguments)
                    input_list.append(
                        {
                            "type": "function_call_output",
                            "call_id": output.call_id,
                            "output": json.dumps({"result": result}),
                        }
                    )
                elif function_name == "duckduckgo_search":
                    result = duckduckgo_search(arguments)
                    input_list.append(
                        {
                            "type": "function_call_output",
                            "call_id": output.call_id,
                            "output": json.dumps({"result": result}),
                        }
                    )
        response2 = get_response2(input_list)
        insert_message(response2.output_text, "ai")
else:
    st.session_state["messages"] = []
    st.sidebar.warning("Input OpenAI API Key.")
